language: python

python:
  - 3.6
  - 3.7

install:
  - pip install codecov
  - python setup.py develop

before_script:
  - flake8 .

script:
  - python setup.py test
  - coverage report

after_success:
  - codecov
